#!/bin/sh
# Script to be executed after a successfull commit.
# 
# Looks for changed files that contain the keywords, removes those files
# and checks them out again to refresh the keywords.

FILES=`ls *.py`
rm -f $FILES
git checkout $FILES

